correios:

  credencial:
    usuario: ${CORREIOS_USUARIO}
    senha: ${CORREIOS_SENHA}
    contrato: ${CORREIOS_CONTRATO:}
    cartao-postagem: ${CORREIOS_CARTAO_POSTAGEM:}
    url-token: ${correios.client.base-url}/token

  client:
    preco-url: ${correios.client.base-url}/preco
    rastro-url: ${correios.client.base-url}/srorastro
    prazo-url: ${correios.client.base-url}/prazo
    prepostagem-url: ${correios.client.base-url}/prepostagem

spring:
  jackson:
    time-zone: America/Sao_Paulo
    default-property-inclusion: NON_NULL
    date-format: "yyyy-MM-dd'T'HH:mm:ss"
    serialization:
      write-empty-json-arrays: false

#-- logging --------------------------------------------------------------------------------------------------------------
logging:
  file:
    name: techday.log